### ISSUE TITLE
head内のfaviconの設定

### ISSUE THREAD

**Issue by oYAs-me** [MutsumeWebDev/75-teaser#34]

**Comment by oYAs-me** [comment]
`<link rel="icon" href="/favicon.png" sizes="any">`を追記するとfaviconとして認識してくれたが、ダークモードのときに色が同化してよく見えない状況になった
![favicon](https://github.com/MutsumeWebDev/75-teaser/assets/69413678/20634f55-4b12-46f7-a267-c6b0964dfeda)
白枠を付けたいが、そういう編集ができる適切なアプリケーションがないので......デザイン部署とかに投げたい
@hamanishi932 一応確認してくれ

**Comment by hamanishi932** [comment]
常にライトモードにできたりしないのかな

**Comment by oYAs-me** [comment]
白背景にするだけで解決しそうだからいいや

**Comment by oYAs-me** [comment]
誰でもできそうだから、新しく入った人がプルリクを体験できるようにしたい
