### ISSUE TITLE
ランディングページ上部の微調整

### ISSUE THREAD

**Issue by hamanishi932** [MutsumeWebDev/75-teaser#41]
タイトルを中央へ変更
scrollimg.cssの微調整（@media(max-width: 540px)でwidth:100%へ変更）
ハンバーガーの大きさを調整（大きく）

**Comment by oYAs-me** [comment]
invalid ラベルは違うんじゃないかな
cf.https://qiita.com/maeda_t/items/4344bdeabcc6a18a34cc

**Comment by hamanishi932** [comment]
enhancementにした、ありがとう
