### ISSUE TITLE
top__imgをmenubar__topに押し込む

### ISSUE THREAD

**Issue by oYAs-me** [MutsumeWebDev/75-teaser#46]
#41 でむつめ祭ロゴが真ん中に来たけど、index以外のページではなくてもよさそう
その代わり、トップページに飛べるリンクをmenubar__topに入れれば大丈夫そうだが......

**Comment by hamanishi932** [comment]
ちょっと手が回らないからもし可能ならやっておいてほしい、、

**Comment by oYAs-me** [comment]
おけ、ちょっと調整するわね

**Comment by hamanishi932** [comment]
サイトソースのほうにこんな感じかなってやつを貼っておくので

**Comment by oYAs-me** [comment]
![headerがかぶってる](https://github.com/MutsumeWebDev/75-teaser/assets/69413678/02eeca4c-ec9f-4006-84b2-a11bf801108f)
のも修正する

**Comment by oYAs-me** [comment]
![実現イメージ](https://github.com/MutsumeWebDev/75-teaser/assets/69413678/333f199d-6e38-4b46-862a-aa83271b4f14)

**Comment by hamanishi932** [comment]
max-width:767px以上のところは,
fabiconを右に持ってきてくれるだけ大丈夫

**Comment by hamanishi932** [comment]
詳細ページのトップのところね

**Comment by hamanishi932** [comment]
menubarの文字の大きさは見やすい感じに調節してくれればOK

**Comment by oYAs-me** [comment]
@hamanishi932 とりあえず要件は満たしたと思う（トリッキーな書き方をしたので少しコメントを入れた）ので、思った通りのものか確認してほしい

**Comment by hamanishi932** [comment]
かなり良いです！！！ありがとうめっちゃ助かる！
