### ISSUE TITLE
hamburger menuが全画面にならない

### ISSUE THREAD

**Issue by oYAs-me** [MutsumeWebDev/75-teaser#56]
VSCode上のプレビューだと全画面になる幅でも、EdgeやFirefoxだと全画面表示されない
ほかの環境でもなるのか検証をしたい

**Comment by hamanishi932** [comment]
max-widthは大丈夫？

**Comment by oYAs-me** [comment]
精読してないからそこまで調査はできてない
今のところはむしろ、そっちの環境で発生するのかどうかのほうが気になってる

**Comment by hamanishi932** [comment]
こっちのedgeローカルだと大丈夫ではある

**Comment by hamanishi932** [comment]
さっきマージしたからそっちに更新してやってみてほしい
一応767px以下でメニューバーが全画面になる設定にしている

**Comment by oYAs-me** [comment]
0424d56e0c0d2bf5a4e23b7e29f161a529978f9b か d52bb365ae1d437005cdbd2bfc2062854b855832 で全画面に修正された
#58 で完全に解決したのでこのissueはクローズします
