### ISSUE TITLE
スマホ横画面だとメニューバーが見切れるかも

### ISSUE THREAD

**Issue by oYAs-me** [MutsumeWebDev/75-teaser#59]
![幅せまスマホを横にしたらメニューバーが見切れる](https://github.com/MutsumeWebDev/75-teaser/assets/69413678/b2546b6d-730c-4e1e-ac83-80c90c4db75a)
上の画像は極端な設定だけど、**メニューバーがスクロールできない**から見切れてしまうと下の項目が見れない/選択できない状況になる
今後項目が増えると普通のスマホでも横画面にするとこういう状況になるかもしれない
@hamanishi932 対応する？

**Comment by hamanishi932** [comment]
スクロールできないのか、、対応したいなあ

**Comment by oYAs-me** [comment]
https://web-note.org/programming/css/drawer-bg-scroll/
これで解決できるかも
