### ISSUE TITLE
index.html内のFor Studentsのブロックの表示乱れ

### ISSUE THREAD

**Issue by oYAs-me** [MutsumeWebDev/75-teaser#62]
![For Students内の表示乱れ](https://github.com/MutsumeWebDev/75-teaser/assets/69413678/50a4b0d7-49aa-488f-812f-e65787a6b374)

**Comment by hamanishi932** [comment]
今やります（シングルカラムにする）

**Comment by oYAs-me** [comment]
SUPPORTと同じような表示形式にしたほうがいいのでは？って思うけどそこはいかがですか？
